// <auto-generated />
namespace CalculoPrecoVenda.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InsereCamposNcm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InsereCamposNcm));
        
        string IMigrationMetadata.Id
        {
            get { return "201701251804460_InsereCamposNcm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
